hollymovies/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from accounts.views import SignupView, user_logout
from viewer.views import home, movie, MoviesListView, CreatorsListView, creator, GenreView, CountryView, \
    CreatorCreateView, CreatorUpdateView, CreatorDeleteView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', home, name='home'),

    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/<pk>/', movie, name='movie'),

    path('creators/', CreatorsListView.as_view(), name='creators'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('creator/<pk>/', creator, name='creator'),

    path('genre/<pk>/', GenreView.as_view(), name='genre'),
    path('country/<pk>/', CountryView.as_view(), name='country'),

    # path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),  # defaultní paths a views z Djanga
]

viewer/models.py
from datetime import date

from django.db.models import Model, CharField, DateField, ForeignKey, SET_NULL, TextField, ManyToManyField, \
    IntegerField, FloatField, DateTimeField


class Genre(Model):
    name = CharField(max_length=20, null=False, blank=False, unique=True)

    class Meta:
        ordering = ['name']  # ascending
        # ordering = ['-name']  # descending

    def __repr__(self):
        return f"Genre(name={self.name})"

    def __str__(self):
        return f"{self.name}"

    def print_to_delete(self):
        return f"žánr '{self.name}'"


class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)
    code = CharField(max_length=3, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Contries"
        ordering = ['name']  # ascending

    def __repr__(self):
        return f"Country(name={self.name}, code={self.code})"

    def __str__(self):
        return f"{self.name}"

    def print_to_delete(self):
        return f"země '{self.name}'"


class Creator(Model):
    name = CharField(max_length=32, null=True, blank=True)
    surname = CharField(max_length=32, null=True, blank=True)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    country_of_birth = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_born')
    country_of_death = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators_died')
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['surname', 'name']  # ascending

    def __repr__(self):
        return f"Creator(name={self.name}, surname={self.surname})"

    def __str__(self):
        return f"{self.name} {self.surname}"

    def age(self):
        if self.date_of_birth:
            end_date = date.today()
            if self.date_of_death:
                end_date = self.date_of_death
            return (end_date.year - self.date_of_birth.year -
                    ((end_date.month, end_date.day) < (self.date_of_birth.month, self.date_of_birth.day)))
        return None

    def print_to_delete(self):
        return f"tvůrce '{self.name} {self.surname}'"


class Movie(Model):
    title_orig = CharField(max_length=150, null=False, blank=False)
    title_cz = CharField(max_length=150, null=True, blank=True)
    genres = ManyToManyField(Genre, blank=True, related_name="movies")
    countries = ManyToManyField(Country, blank=True, related_name="movies")
    actors = ManyToManyField(Creator, blank=True, related_name="acting")
    directors = ManyToManyField(Creator, blank=True, related_name="directing")
    length = IntegerField(null=True, blank=True)  # min
    released = IntegerField(null=True, blank=True)  # year
    description = TextField(null=True, blank=True)
    rating = FloatField(null=True, blank=True)  # 0-100
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig', 'released']  # ascending

    def __repr__(self):
        return f"Movie(title_orig={self.title_orig})"

    def __str__(self):
        return f"{self.title_orig} ({self.released})"

    def length_format(self):
        hours = self.length // 60
        minutes = self.length % 60
        if minutes < 10:
            minutes = f"0{minutes}"
        return f"{hours}h {minutes}min"

    def print_to_delete(self):
        return f"film '{self.title_orig} ({self.released})'"


# TODO: Review
"""
Review
- user -> Profile  # TODO: Profile -> User (Django)
- movie -> Movie
- review: string
- rating: int(0 - 100)
"""

# TODO: Images

templates/base.html
<!DOCTYPE html>
{% load static %}

<html {% if LANGUAGE_CODE %}
    lang="{{ LANGUAGE_CODE }}"
{% else %}
    lang="en"
{% endif %}
>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <!-- Custom CSS -->
    <style>
        footer {
            text-align: center;
        }
    </style>
</head>

<body>

{% include "navbar.html" %}

<div class="container">
    <div class="jumbotron">
        {% block content %}{% endblock %}
    </div>
</div>

{% include "footer.html" %}

</body>

</html>

templates/footer.html
<footer>
    PythonRemoteCZ23 - Backend technologies
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">HollyMovies</a>
        <button
                class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'home' %}">Domů</a>
                <a class="nav-item nav-link active" href="{% url 'movies' %}">Filmy</a>
                <a class="nav-item nav-link active" href="{% url 'creators' %}">Tvůrci</a>
                {% comment %}
                {% if user.is_authenticated %}
                {% endcomment %}
                {% if perms.viewer.add_creator %}
                    <a class="nav-item nav-link active" href="{% url 'creator_create' %}">Přidat tvůrce</a>
                {% endif %}

                {% comment "TODO: actors" %}
                <a class="nav-item nav-link active" href="{% url 'actors' %}">Herci</a>
                <a class="nav-item nav-link active" href="{% url 'directors' %}">Režiséři</a>
                {% endcomment %}

            </div>
        </div>

        <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'logout' %}">Odhlásit</a>
                        <a class="dropdown-item text-right" href="{% url 'password_change' %}">Změnit heslo</a>
                        <a class="dropdown-item text-right" href="{% url 'password_reset' %}">Resetovat heslo</a>
                    </div>
                {% else %}
                    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                        Nepřihlášený uživatel
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item text-right" href="{% url 'login' %}">Přihlásit</a>
                        <a class="dropdown-item text-right" href="{% url 'signup' %}">Registrovat</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>